### ISSUE TITLE
New lastfm

### ISSUE THREAD

**Issue by enricll** [xxdavid/lastfm-friends-who-listen#12]
Last.fm has recently [changed its design](https://getsatisfaction.com/lastfm/topics/website-design-update-rolling-out-today) for albums, songs, and artists pages (even though it's not available  yet to every single user). Any plans to update the extension to accommodate the widget in the new design/layout? Thanks.

**Comment by xxdavid** [comment]
Hi, my Last.fm looks still the same to me and the extension is still working for me. Do _you_ have the new design?

**Comment by hans-juergen** [comment]
Hi David, the new website design is still being rolled out to all Last.fm users, but subscribers are now able to see it. I can confirm that your browser extension does not work any longer with it. I posted [some screenshots](https://getsatisfaction.com/lastfm/topics/when-is-the-new-website-design-update-coming-out-for-non-subscribers-its-been-two-months-since-the-announcement?topic-reply-list[settings][filter_by]=all&topic-reply-list[settings][reply_id]=19954569#reply_19954569) of the new design in a related thread some weeks ago. There also is a [related Reddit thread](https://www.reddit.com/r/lastfm/comments/b2eu4d/any_good_browser_extensions/eiv94gp/) about Friends Who Listen currently not working for subscribers.

**Comment by xxdavid** [comment]
Hi Hans, thank you for your never-ending support!
If you could send me the HTML of some artist pages, we possibly may get it working even berfore the new design is rolled out to me. :)

**Comment by hans-juergen** [comment]
Sure, I will send the saved HTML pages of Peter Gabriel, his album "So" and the track "In Your Eyes" in a ZIP file to your email address mentioned on your GitHub profile. Is that enough, or do you also need the subfolders saved with them containing more files?

**Comment by xxdavid** [comment]
Fixed by #15. It should be working now (updated Firefox version is in the store, Chrome version is waiting for a review).
